### ISSUE TITLE
Problem crafting wood chests and wood doors

### ISSUE THREAD

**Issue by Alant2505** [MinestrapTeam/Minestrappolation-4#102]
I tried both versions 4.0.2 A and 4.2 and I came up with an issue, I was not able to craft neither wood chests nor wood doors. Y finally delete the game, reinstalled it and only used Minestrapp 4.2 with forge 1.8 and found out that it was this mod which caused de chests bug... Just wanted you to be aware of this, maybe it´s not the mod, but me and my pc... But in my case, it was minestrap who was causing that trouble. In case that it's true I really hope you guys can fix it, because it is a great mod. Best regards!

**Comment by werty1124** [comment]
There is not bug with crafting them. You have to use a carpenters bench!

**Comment by jpiermarini** [comment]
@werty1124 How is not being able to craft wood chest and wood doors in the vanilla crafting table not a bug? I should not need to get cooper and craft a carpenters bench to make simple items such as that.
