### ISSUE TITLE
Final Release for 1.8.9

### ISSUE THREAD

**Issue by Clashsoft** [MinestrapTeam/Minestrappolation-4#118]
Before upgrading the mod to Minecraft v1.9 and Major Version 5, we should consider releasing a final release that targets 1.8.9. There are two possible options:
### Releasing a patch: _Minestrappolation 4.3.1_

Fairly straight-forward patch/bugfix release. As required by the versioning scheme, the patch version number increase means only bugfixes and potentially balancing, no new features or removals. The current state of the repository does not have the necessary integrity for this though, since new features have already been added since the last release. Removing these can be done using Git magic, but at the cost of maybe resetting bug fixes as well.
### Releasing a new minor version: _Minestrappolation 4.4.0_

This option requires a fair bit more work. New features have been added, but still require extensive testing and likely bug fixing. Seeing the time constraints and the recent release of Forge for 1.9, it is probably not possible to include all planned features. This means release plans have to be changed drastically.

**Comment by Delocuro** [comment]
Eh — at this point, our versioning system doesn't really follow any consistent pattern at all, so there's not a lot of point trying to start one until we hit some major landmark like 5.0. I've just been increasing the version numbers based on the quantity of content added, so considering how small this one is, it'd probably be 4.3.1 if it's just bugfixes or 4.3.2/4.3.3 if it has a few features.

We don't really have any set release dates for anything at this point though, so if we're going to squeeze in another small 1.8.9 update, we might as well feature creep a little too. Once I get my desktop set up again I should be able to cram out a lot of those bug fixes and balance changes really fast, so I'll probably start feature creeping after that and we'll plan on releasing whatever we have polished in like a week or so if it seems pretty releasable.

**Comment by Clashsoft** [comment]
It's never to late to introduce a consistent versioning scheme, because without one, it gets confusing really fast. Incrementing any number by more than one is a bad idea as well. Besides, it doesn't hurt to go to 4.4 if you really want to include features.

**Comment by Delocuro** [comment]
Closing this for now, since we're having enough trouble without extra features and code changes to worry about. We'll have to figure out versioning and such closer to release -- if 1.10 forge comes out before we finish updating to 1.9, we may want to just skip a 1.9 release and move on to 1.10.
