### ISSUE TITLE
Add All the Ores

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Minestrappolation-4#2]
I can probably do this since it's relatively simple, but all the old Ores eventually need to be added back in.
- [X] Re-add Slate.
- [X] Re-add Desert Quartz.
- [X] Re-add Meurodite Ore.
- [X] Re-add Torite Ore.
- [X] Re-add Uranium Ore.
- [X] Re-add Plutonium Ore.
- [X] Re-add Radiant Quartz Ore.
- [X] Re-add Titanium Ore.
- [X] Re-add Blazium Ore.
- [X] Re-add Soul Ore.

**Comment by werty1124** [comment]
Assigned you Erik since you right its easy :p gives me more time to work on the redwood stuff
