### ISSUE TITLE
Crate & Barrel Issues

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Minestrappolation-4#22]
- [X] Crates and Barrels are not treated as transparent blocks -- thus, they let you xray through the ground when placed next to solid blocks.
- [X] Crates and Barrels have no hardness or blast resistance.
- [X] All Barrel GUI slots are two pixels lower than they should be (including the player's inventory)..

**Comment by werty1124** [comment]
Gonna let you set the hardness and blast resistance
