### ISSUE TITLE
Add Biome-Specific Stone Textures

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Minestrappolation-4#3]
This one's a bit more optional, since I don't know that the old generation method actually works anymore (EDIT: They all generate right just have to add the blocks). If you feel like taking a stab at it, though, feel free.
- [X] Re-add Deepstone.
- [X] Re-add Red Rock.
- [X] Re-add Deep Red Rock.
- [X] Re-add Coldstone.
- [X] Re-add Deep Coldstone.
- [X] Re-add Icestone.
- [X] Re-add Glacierrock.
- [X] Re-add Oceanstone.
- [X] Re-add Pressurized Oceanstone.
- [ ] Texture and name all stones

**Comment by werty1124** [comment]
![2015-04-29_03 31 01](https://cloud.githubusercontent.com/assets/5126851/7386309/33095092-ee20-11e4-9f84-267c9353b4ce.png)

A Cave of coldstone just for proof :p
