### ISSUE TITLE
Minstrapp 4.0.0 issues

### ISSUE THREAD

**Issue by medsal15** [MinestrapTeam/Minestrappolation-4#32]
- [X] Missing names. Everything is "item/tile/{nothing}_something.name"
- [x] Missing textures. Roads only.
- [X] Weird models in inventory. Stairs only.
- [x] Missing recipies. Diamonds tools, meat block.
- [x] Missing feature: Redwood doors can only be crafted with the sawmill, its vanilla version can be made with a normal crafting table. 
- [X] Fire sword doesn't set mobs on fire. 
- [ ] Zombies get the wither effect when exposed to the plutonium block.
  Screenshots:
  1:
  ![2015-05-28_12 34 47](https://cloud.githubusercontent.com/assets/8267354/7858244/03aedec4-0537-11e5-9921-2bd2298b4d72.png)
  ![2015-05-28_12 34 53](https://cloud.githubusercontent.com/assets/8267354/7858243/03ad77be-0537-11e5-8966-27a437c08737.png)
  2: 
  ![2015-05-28_12 37 02](https://cloud.githubusercontent.com/assets/8267354/7858355/e374328e-0537-11e5-9dfb-f803b223f254.png)
  3: Replace the name by tile.X_stairs.name
  4: 
  ![2015-05-28_12 38 36](https://cloud.githubusercontent.com/assets/8267354/7858385/047b12fe-0538-11e5-80ff-b8a3f18a97b6.png)
  ![2015-05-28_12 38 37](https://cloud.githubusercontent.com/assets/8267354/7858386/047b87b6-0538-11e5-8964-cc11a91ecc52.png)
  5: 
  ![double-crafting](https://cloud.githubusercontent.com/assets/8267354/7858441/53ddbe1e-0538-11e5-89c8-6350cbb778ac.png)
  ![2015-05-28_12 39 16](https://cloud.githubusercontent.com/assets/8267354/7858394/16bb7a12-0538-11e5-918e-d9ecc3bbf5bf.png)
  6:
  ![2015-05-28_12 40 10](https://cloud.githubusercontent.com/assets/8267354/7858417/2cdf90d0-0538-11e5-89b1-c84fdf4ebd37.png)
  ![2015-05-28_12 40 16](https://cloud.githubusercontent.com/assets/8267354/7858414/2cdd60bc-0538-11e5-9aad-4a6b0b35ce57.png)
  ![2015-05-28_12 40 34](https://cloud.githubusercontent.com/assets/8267354/7858415/2cdde596-0538-11e5-8325-7343693625db.png)
  ![2015-05-28_12 40 40](https://cloud.githubusercontent.com/assets/8267354/7858412/2cdbfe34-0538-11e5-9a1d-ba7858813e15.png)
  ![2015-05-28_12 41 00](https://cloud.githubusercontent.com/assets/8267354/7858416/2cde1d22-0538-11e5-9d8b-d0642c34f64a.png)
  ![2015-05-28_12 41 02](https://cloud.githubusercontent.com/assets/8267354/7858413/2cdc7f08-0538-11e5-90a9-0393f598646d.png)

**Comment by Delocuro** [comment]
Missing road textures are a known issue and were fixed like two commits after we released the pre-alpha, but the other stuff is good to know. Very confused as to why the Diamond Tools recipes and item/block localizations are messed up, though. Seem to be working fine in the dev environment...

**Comment by werty1124** [comment]
Good finds. The localizations are definitely weird because they are working fine in my dev workspace

**Comment by werty1124** [comment]
What version of Forge did you have?

**Comment by medsal15** [comment]
1419

**Comment by Delocuro** [comment]
Oooooh, wait, just figured out the names issue. Are you using a language setting other than U.S. English? Because that's the only supported lang file currently, so that'd make sense that all the names would be broken...

**Comment by werty1124** [comment]
Yea that could definitely be the cause of that. Medsal if you were using another language it would be great if you wanted to make a lang file for it!
