### ISSUE TITLE
Sifter Tables don't support ItemStacks or Blocks.

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Minestrappolation-4#38]
Fortunately the game doesn't crash if I try to add ItemStacks or Blocks to the lists of possible Sifter drops, but those objects will never actually drop from their respective blocks if added. This basically means the Sifter can't drop anything that isn't a metadata-less item, which kind of limits its possibilities.

**Comment by werty1124** [comment]
It does support blocks you just have to use Item.getItemFormBlock I think thats what its called.
and if you change Chance.createChanceTable("sifter_sand", new ArrayList Item  to Chance.createChanceTable("sifter_sand", new ArrayList ItemStack it supports item stacks :p
