### ISSUE TITLE
Villager Trades

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Minestrappolation-4#40]
Custom Minestrapp Villager trades haven't been re-added yet, so that should probably get done eventually. Didn't put this under the Alpha checklist, since it's not as necessary to add before we release.

**Comment by werty1124** [comment]
This is not possible at the moments Forge has to re-write the villager stuff before it will apparently.

**Comment by Delocuro** [comment]
Merged into the new "stretch goals" issue since it's not currently possible.
