### ISSUE TITLE
Crusher "0" Quantity Extra Drops

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Minestrappolation-4#55]
Occasionally, crushing an item that has a chance to give an extra drop will produce the drop, but with a quantity of 0 instead of the set amount. There doesn't seem to be any pattern as to when this happens from what I can tell, and most of the time it works fine.

**Comment by werty1124** [comment]
Yea i noticed this too. Haven't really look much into it though ill take a look at it right now
