### ISSUE TITLE
Textures, Errors, Bugs, Suggestions, Etc.

### ISSUE THREAD

**Issue by deepslater** [MinestrapTeam/Minestrappolation-4#66]
Some things I've found:

suggestion: Maybe the glass bottle isn't consumed with the recipe, just the water?)

Using the latest version of Waila causes all sorts of texture flashes and overall visual glitches.

Suggestion: make biome ores have normal mining speed because mining deepstone should require iron, but mining coal and iron in that layer takes an incredibly long time.

**Comment by werty1124** [comment]
Deepstone is meant to be harder then the regular stone type. As for the other things you mentioned they have been fixed

**Comment by deepslater** [comment]
I understand, what I mean is that ores surrounded by biome stones take on the hardness of their surroundings. This makes coal, which should be fast with an iron tool, take a very long time. I just think that the ores should be normally mined while deepstone and other deep stones should remain how they are.
