### ISSUE TITLE
Brick Items Lack Valid Localization Entries

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#73]
from nightly build 216 bricks were changed to use metadata, this made their localization entries not valid (in previous builds they were showing correctly),
changing `items.stone_brick.name=Stone Brick` to `stone_brick.name=Stone Brick` in `en_US.lang` for all sixteen brick item entries respectively makes them valid again

**Comment by Delocuro** [comment]
Just noticed that one right before I saw this, lol. We're planning on doing a small bugfix update soon to fix a few of the more notable 3.1.0 issues, so we'll make sure that's fixed before it comes out.

**Comment by Delocuro** [comment]
Merged into #87.
