### ISSUE TITLE
crusher nei related crash/issues

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#74]
tested using

```
multimc 5 0.4.7
forge 11.14.3.1502
minestrappolation nightly 234
nei recommended
    codechickencore 1.8-1.0.5.34
    notenoughitems 1.8-1.0.5.82
nei latest
    codechickencore 1.8-1.0.5.36
    notenoughitems 1.8-1.0.5.104
```
- in crushers interface, "Recipes" tooltip is displayed when hovering mouse cursor below progress arrow/indicator
- crash when clicking progress arrow/indicator - nei reciepes lookup
  - nei recommended, [log](https://paste.ee/p/OQ1aX)
  - nei latest, [log](https://paste.ee/p/ihSOZ)
- inconsistent behaviour, i.e. gold ore shows only furnace smelting for recipes using it, recipes outputting gold ore chunk show crusher recipes using gold ore

**Comment by werty1124** [comment]
Crusher recipes have been temp removed from NEI. They will be added back soon.
