### ISSUE TITLE
Server Console Spam

### ISSUE THREAD

**Issue by TotalHamman** [MinestrapTeam/Minestrappolation-4#75]
My server console is being spammed with the following message approximately once a minute.  It does not appear in any logs that I can find.

new protection data is saved in Minestrapp/world/chunkster.pcznew protection data is saved in Minest
rapp/world/chunkster.pcz

**Comment by werty1124** [comment]
It should only appear when the world is saved. How often does your server auto-save?

**Comment by TotalHamman** [comment]
I have not adjusted world save frequency, so whatever is default 1.8.

However the issue went away when I upgraded to 4.1.0.  

Now though, I am getting spam in the server console every time an ore is mined.  The spam consists of the number 0, one per row, and one row per item dropped from mining the ore.

Seems like a debug statement is still activated.

**Comment by werty1124** [comment]
Yep looks like your right I'll remove it. Not even sure what it's purpose was for now.
