### ISSUE TITLE
Melter in "Boosted" Mode Can Become Stuck After Fuel Consumption

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#76]
melter in "boosted" mode (activated by redstone signal) in some cases will lose its melting progress and become stuck/unresponsive until picked up and replaced,
[video demo](https://gfycat.com/FoolhardyObedientHaddock)
- example 1
  - place melter
  - insert cobblestone in input slot
  - insert empty bucket in bucket slot
  - insert stack of sticks into fuel slot
  - melting process will start
  - apply redstone signal to enable "boost" mode
  - melting process will stop and machine will become unresponsive
- example 2
  - place melter
  - apply redstone signal
  - insert cobblestone
  - insert empty bucket
  - insert 1 coal
  - wait for fuel to be consumed and process to pause
  - insert 1 stick
  - stick will be consumed, melting will reset and machine will become unresponsive

**Comment by Delocuro** [comment]
Merged into #87.
