### ISSUE TITLE
Crusher Deletes Processed Item Bonus Slot Output if Other Item Already Occupies It

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#77]
slate has 80% chance to output desert quartz in bonus slot,
place anything but desert quartz in bonus output slot manually or by other item being processed by crusher,
place stack of slate in input slot,
place fuel in fuel slot,
slate will be processed and no bonus items will be generated until something other than desert quartz is in bonus slot

**Comment by werty1124** [comment]
Interesting. Really appreciate the video, I'll look into it!

**Comment by Delocuro** [comment]
Merged with #87.
