### ISSUE TITLE
bushes can grow in darkness, can be stacked

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#78]
![8596338108c5e55508ff6019d768785f](https://cloud.githubusercontent.com/assets/13768838/9284294/ee43498a-42da-11e5-959b-40cb4f4880b7.png)
- bushes can grow in complete darkness,
- bushes of the same type can be stacked on top of each other until world limit

**Comment by werty1124** [comment]
These are intentional. Well being stack-able.
