### ISSUE TITLE
Using Pick Block (Creative Mode) on Active Machine Gives Active Machine Block Version

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#79]
using "pick block" (middle mouse button in creative mode) on machine during work cycle will give its "active" block version
- active alloy furnace - `tile.alloy_active.name` block
- active melter - `tile.melter_active.name` block
- active ore crusher - `tile.crusher_active.name` block
- active alchemical splitter - `tile.splitter_active.name` block

**Comment by Delocuro** [comment]
Merged with #87.
