### ISSUE TITLE
Soul Ore Nether Wart Only Drops Soul Gems when Harvested by Players

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#81]
mature nether wart planted on soul ore will drop soul gems only when it is harvested by a player,
it will not drop soul gems when uprooted by:
- moving soul ore by piston,
- breaking soul ore block,
- flowing water stream,

to aid testing set in minestappolation config `SoulGemDropChance=100` and in game issue command `/gamerule randomTickSpeed 3000` (default value 3) to accelerate growth

**Comment by Delocuro** [comment]
We'll see if we can fix that soon, but it'll be a bit lower priority, since I'm not sure if there's an event method for detecting when blocks are destroyed by an entity other than the player...
