### ISSUE TITLE
Typo in "pressurized_oceanstone_lamp_sunstone.name" Localization Entry

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#89]
currently is `pressurized_oceanstone_lamp_sunstone.name=Pressurized  Sunstone Lamp`,
should be `pressurized_oceanstone_lamp_sunstone.name=Pressurized Oceanstone Sunstone Lamp`

**Comment by Delocuro** [comment]
Merged with #87.
