### ISSUE TITLE
Splitter Stops Processing After Removing Items from One of Occupied Output Slots

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#91]
processing of stacked items in input slot will not continue after removing items from one of the output slots,
[video demo](http://gfycat.com/AccomplishedPerkyHadrosaurus)

**Comment by dportuesi** [comment]
This is on purpose, so you cant change the current splitting item and lose your stuff when it over-rights what's currently in the output slots.
