### ISSUE TITLE
Crash, it's odd

### ISSUE THREAD

**Issue by SnapshotDesign** [MinestrapTeam/Minestrappolation-4#92]
WARNING: coremods are present:
  NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  LoadingScreenLoadPlugin (Better-Loading-Screen-Mod-1.8.jar)
  CorePlugin (MakersMark-V2.0.1-MC1.8.jar)
  LoadPlugin (AlexIILLib-1.8.jar)
  TransformerLoader (OpenComputers-MC1.8-1.5.11.28-universal.jar)
  LoadingPlugin (RandomThings-MC1.8-3.5.3.jar)
  FMLPlugin (InventoryTweaks-1.59-176.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  CCCDeobfPlugin (unknown)
  CoreMod (Aroma1997Core-1.8-1.0.3.4.b36.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  CAFMLPlugin (Craftable-Animals-Mod-1.8.jar)
  VeinMinerCorePlugin (VeinMiner-1.8_0.27.0.unknown.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 8/18/15 2:52 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: minestrapteam.mods.minestrappolation.Minestrappolation
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:538)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:413)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: minestrapteam.mods.minestrappolation.Minestrappolation
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:60)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:445)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:507)
    ... 10 more
Caused by: java.lang.UnsupportedClassVersionError: minestrapteam/mods/minestrappolation/Minestrappolation : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 37 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Mac OS X (x86_64) version 10.9.5
    Java Version: 1.6.0_65, Apple Inc.
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Apple Inc.
    Memory: 205946552 bytes (196 MB) / 393777152 bytes (375 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1502 137 mods loaded, 137 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.3.1502.jar) 
    UC  Forge{11.14.3.1502} [Minecraft Forge](forge-1.8-11.14.3.1502.jar) 
    UC  Aroma1997Core{1.0.3.4.b36} [Aroma1997Core](Aroma1997Core-1.8-1.0.3.4.b36.jar) 
    UC  CodeChickenCore{1.0.5.34} [CodeChicken Core](minecraft.jar) 
    UC  NotEnoughItems{1.0.5.104} [Not Enough Items](NotEnoughItems-1.8-1.0.5.104-universal.jar) 
    UC  OpenComputers|Core{1.0.0} [OpenComputers (Core)](minecraft.jar) 
    UC  VeinMiner_coremod{0.26.1_build.unknown} [Core mod](minecraft.jar) 
    UC  hitchcore{1.0.0} [HitchH1k3r's Mods](minecraft.jar) 
    UC  zeldaswordskills{1.8-3.0.3} [Zelda Sword Skills](1.8-zeldaswordskills-3.0.3.jar) 
    UC  rockcandy{1.0} [Rock Candy Mod by Dralard](1.8.x_Rock_Candy_Mod_1.0_by_Dralard.jar) 
    UC  moSwords{v6} [Mo Swords Mod]([1.8] moSwords v6.jar) 
    UC  bspkrsCore{7.01} [bspkrsCore]([1.8]bspkrsCore-universal-7.01.jar) 
    UC  DamageIndicatorsMod{3.3.3} [Damage Indicators]([1.8]DamageIndicatorsMod-3.3.3.jar) 
    UC  fallout{[1.8] v0.2.2.1} [The Fallout Mod]([1.8]Fallout v0.2.2.1.jar) 
    UC  spectralguns{1.2.2} [Spectral Guns]([Forge 1.8] SpectralGuns 1.2.2.jar) 
    UC  adminweapons{2.5} [Admin Weapons](adminweapons-v2.6-mc1.8.jar) 
    UC  AfraidOfTheDark{1.8-1.0} [Afraid of the Dark](AfraidOfTheDark-1.8-1.0.2.jar) 
    UC  alexiillib{0.1} [AlexIILLib](AlexIILLib-1.8.jar) 
    UC  animalbikes{1.8} [Animal Bikes](AnimalBikes_1.8.0.jar) 
    UC  uap{1.1.0} [Animal Research Machine](AnimalResearchMachine-15.6.26-1.0.0-1.8.jar) 
    UC  antiqueatlas{4.2.4-1.8} [Antique Atlas](antiqueatlas-4.2.4-1.8.jar) 
    UE  ArchitectureCraft{1.0.0} [ArchitectureCraft](ArchitectureCraft-Mod-1.8.jar) 
    UC  Aroma1997CoreHelper{1.0.3.4.b36} [Aroma1997Core|Helper](Aroma1997Core-1.8-1.0.3.4.b36.jar) 
    UC  Backpack{2.0.1} [Backpack](Backpacks-Mod-1.8.jar) 
    UC  Baubles{1.1.0.0} [Baubles](Baubles-1.8-1.1.0.0.jar) 
    UC  beautifulvanilla{1.0} [beautifulvanilla](beautifulvanilla-0.31.jar) 
    UC  betterloadingscreen{1.8-1.3.1.52} [Better Loading Screen](Better-Loading-Screen-Mod-1.8.jar) 
    UE  betterbeginnings{0.9.1-pre1} [Better Beginnings](betterbeginnings-MC1.8.0-b0.9.1-pre1.jar) 
    UC  bettermining{0.1} [Better Mining](BetterMining-1.8.6.jar) 
    UC  BiomesOPlenty{1.0} [Biomes O' Plenty](BiomesOPlenty-1.8-3.0.0.1017-universal.jar) 
    UE  biowarfare{1.0} [BioWarfare](BioWarfare 0.1.0.8 mc1.8.jar) 
    UC  AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8-1.4.0-1.jar) 
    UC  buildingtools{0.0.5} [Building Tools](buildingtools-0.0.5-mc1.8.jar) 
    UC  butterflymania{1.5} [Butterfly Mania](butterflymania-1.8-1.5.jar) 
    UC  C4Lib{1.0.0} [C4Lib](C4Lib-1.8-1.0.0-universal.jar) 
    UC  grim3212core{V0.1 - 1.8} [Grim3212 Core](Grim3212-Core-1.8.jar) 
    UC  calendar{V0.1 - 1.8} [Calendar](Calendar-Mod-1.8.jar) 
    UC  codknives{V0.1 - 1.8} [Call of Duty Knives](Call-of-Duty-Knives-Mod-1.8.jar) 
    UC  chiselsandbits{1.0} [Chisels & Bits](Chisels-and-Bits-Mod-1.8.jar) 
    UC  confighealth{2.1} [Configurable Health](Configurable-Health-Mod-1.8.jar) 
    UC  MINE_CONTAINER{1.0} [Container capture](Container Capture Mod 1.8.jar) 
    UC  CookingPlus{0.0.1} [CookingPlus](CookingPlus-0.1.jar) 
    UE  CraftableAnimals{2.5.0.0} [Craftable Animals](Craftable-Animals-Mod-1.8.jar) 
    UC  customnpcs{1.8.0_beta} [CustomNpcs](CustomNPCs_1.8.0_beta.jar) 
    UE  wonderfulwands{1.6.1} [Wonderful Wands](CyanosWonderfulWands-1.6.1-2.jar) 
    UC  decorationmegapack{1.18} [Decoration Mega Pack](decorationmegapack-1.18-1.8-1446.jar) 
    UC  MoCreatures{8.0.0.devA} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod-8.0.0.devA-2.jar) 
    UC  emeraldobsidianmod{1.2} [Emerald & Obsidian tools/armor mod](Emerald-and-Obsidian-Tools-Mod-1.8.jar) 
    UC  eplus{3.1.0a1} [Enchanting Plus](EnchantingPlus-1.8-3.1.0a1.jar) 
    UC  mdecore{1.8-1.2.2} [MattDahEpic Core](mdecore-1.8-1.2.2.jar) 
    UC  exchangeorb{1.8-1.8} [Exchange Orb](exchangeorb-1.8-1.8.jar) 
    UC  exnihilo2{0.27} [Ex Nihilo 2](ExNihilo2-0.27.jar) 
    UC  exoticbirds{1.0} [Exotic Birds](Exotic-Birds-Mod-1.8.jar) 
    UC  eyemod{5.5} [EyeMod](eyemod-5.5.jar) 
    UC  ezstorage{1.0} [EZ Storage](ezstorage-1.0.jar) 
    UC  fakeores{2.0} [Fake Ores 2](fakeores2v1-mc1.8.jar) 
    UC  fancypack{V0.1 - 1.8} [Fancy Pack](FancyPack-Mod-1.8.jar) 
    UC  FantasticFood{1.8} [FantasticFood](Fantastic-Foods-Mod-1.8.jar) 
    UC  extinguisher{V0.1 - 1.8} [Extinguisher](Fire-Extinguisher-Mod-1.8.jar) 
    UC  fireplacecore{2.3.2.0} [Fireplace Core](Fireplace Core 2.3.2.0.jar) 
    UC  flansmod{5.0} [Flan's Mod](Flan's Mod-1.8-5.0.jar) 
    UC  ftea{1.8b} [Flower Tea](Flower Tea 1.8b.jar) 
    UC  forge_TheEpicarnoMod{V1.1.4.6} [The Epicarno Mod](forge_TheEpicarnoMod-1.1.4.6.jar) 
    UC  furbymania{beta2} [Furby Mania](furbymania-1.8-beta2.jar) 
    UC  gadgetsngoodies{BETA} [Gadgets n' Goodies Mod](Gadgets_n_Goodies_mod_v1.1_mc_v1.8.jar) 
    UC  geoactivity{2.0} [GeoActivity](geoactivity-2.0.jar) 
    UC  fishing{1.1} [Fishing Net Mod](GiacomosFishingNet1.8-1.1.jar) 
    UC  gravitycontrol{V0.1 - 1.8} [Gravity Controller](Gravity-Control-Mod-1.8.jar) 
    UC  iChunUtil{5.4.0} [iChunUtil](iChunUtil-5.4.0.jar) 
    UC  GravityGun{5.0.0} [GravityGun](GravityGun-5.0.0.jar) 
    UC  HelperTools{v2.5b} [HelperTools](HelperTools-1.8.0-v2.5b.jar) 
    UC  imc{1.8.0} [Improving Minecraft](Improving Minecraft-1.8.0.jar) 
    UC  inventorytweaks{1.59-176-9318a76-dirty} [Inventory Tweaks](InventoryTweaks-1.59-176.jar) 
    UC  IronChest{6.0.84.743} [Iron Chest](Iron-Chests-Mod-1.8.jar) 
    UC  fyberbackpack{1.0} [Just Backpacks](justbackpacks-mc1.8-1.0.jar) 
    UC  km{1.0} [Kruuxtian Magiks](Kruuxtian Magiks-1.0.0.1.jar) 
    UC  LotsOfFood{1.8.0} [Lots of Food](Lots of Food-1.8.0.jar) 
    UC  LOT{1.0} [ß9ßlLots of Things](Lots-of-Things-1.0-[1.8].jar) 
    UC  magicclover{0.6} [Magic Clover](Magic-Clover-Mod-1.8.jar) 
    UC  magicyarn{1.1.6} [Magic Yarn](MagicYarn-1.8.jar) 
    UC  makersmark{2.0.1} [Maker's Mark: The Minter's Mod](MakersMark-V2.0.1-MC1.8.jar) 
    UC  chef{4.0} [Master Chef](Master_Chef_v4.0-1.8.jar) 
    UE  ministrapp{1.8.0-4.1.0} [Minestrappolation Mod](Minestrappolation-1.8-4.1.0.jar) 
    UC  MinesweeperMod{1.5.0} [Minesweeper Mod](Minesweeper Mod-1.8-1.5.0.jar) 
    UC  ms{v1.66} [MoShiz](Mo' Shiz v1.66.jar) 
    UC  mobdropexchangeorb{1.8-1.5.1} [Mob Drop Exchange Orb](mobdropexchangeorb-1.8-1.5.1.jar) 
    UC  modmercenario{1.8} [modmercenario](modmercenario-0018_1.8.jar) 
    UC  me{1.3.2.1} [More Enchantments](MoreEnchantments-1.8-1.3.2.1.jar) 
    UC  AencEx{0.0.1} [AencEx](MoreEnchantments-1.8-1.3.2.1.jar) 
    UC  MoreFurnaces{1.3.10} [More Furnaces](MoreFurnaces-1.3.10-MC1.8.jar) 
    UC  cfm{3.4.8} [ß9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8-build1%281.8%29.jar) 
    UC  myfit{1.9} [MyFit](myfit-v1.9.jar) 
    UC  nuclearcraft{V0.1 - 1.8} [Nuclear Craft](Nuclear-Craft-Mod-1.8.jar) 
    UC  oldguns{1.3.0} [Old Guns Mod](oldguns-1.3.0_x32.jar) 
    UC  OpenComputers{1.5.11.28} [OpenComputers](OpenComputers-MC1.8-1.5.11.28-universal.jar) 
    UC  Paintball{1.8.0v1} [Paintball](Paintball-1.8.0v1.jar) 
    UE  pandorasbox{2.1.2} [Pandora's Box](PandorasBox-2.1.2.jar) 
    UC  parachutemod{3.1.1} [Parachute Mod](parachutemod-1.8.0-3.1.1-23.jar) 
    UC  pocketnether{1.3} [Pocket Nether Link Mod](pocketnether-1.8-1.3.jar) 
    UC  pokeball{V0.1 - 1.8} [Pokeball](Pokeball-Mod-by-grim3212-1.8.jar) 
    UC  pcb{1.3} [Portable Craft Bench](Portable Craft Bench Mod 1.8.jar) 
    UC  projectbench{0.5.0} [Project Bench Updated](ProjectBench-Update-1.8-0.5.0.jar) 
    UC  ProjectE{1.8-PE1.0.1B} [ProjectE](ProjectE-1.8-PE1.0.1B.jar) 
    UC  RandomThings{3.5.3} [Random Things](RandomThings-MC1.8-3.5.3.jar) 
    UC  corerm{1.2c} [RikMuld's Core](RikMuldsCore_1.2c.jar) 
    UC  rpcraft{Beta 1.3 - 1.8.0} [RP Craft](rpcraft-1.3-1.8.0.jar) 
    UC  showarmsstand{1.1} [ShowArmsStand](ShowArmsStand-1.8-1.1.jar) 
    UC  sigurdsEpicAdventureStuff{1.0.1} [Sigurd's Epic Adventure Stuff!](SigurdsEpicAdventureStuff-1.0.1-mc1.8.jar) 
    UC  SilentGems{1.3.00} [Silent's Gems](Silents-Gems-Mod-1.8.jar) 
    UE  SimilsaxTranstructors{1.8.0.5} [Similsax Transtructors](SimilsaxTranstructors-1.8.0.5.jar) 
    UC  samsbeetroot{1.8-1.0.0} [Simple Beetroot](SimpleBeetroot-1.8-1.0.0.jar) 
    UC  SlimevoidLib{3.0.0.4-beta-1.8} [Slimevoid Library](SlimevoidLibrary-3.0.0.4-beta-1.8.jar) 
    UC  snowconecraft{1.8-1.0} [Snow Cone Craft](Snow-Cone-Craft-Mod-1.8.jar) 
    UC  soda{V0.1 - 1.8} [Soda](Soda-Mod-1.8.jar) 
    UC  spawnercraft{1.8-2.0a} [SpawnerCraft](SpawnerCraft2-1.8-2.0a.jar) 
    UC  supersentai{1.0.0} [SuperSentai](SuperSentaiMod-v.1.0.0-forge-1.8-11.14.1.1341.jar) 
    UC  telepacks{1.8-1.0} [TelePacks](telepacks-1.8-1.0.jar) 
    UC  cursedarmourmod{1.0} [The Consecrated Armour Mod](The Consecrated Armour Mod for Minecraft 1.8.jar) 
    UC  elementsmod{1.0.5} [The Elements Mod](The Elements Mod [1.0.5b] for Minecraft 1.8.jar) 
    UC  camping{2.2e} [The Camping Mod 2](TheCampingMod_2.2e.jar) 
    UC  throwabletorchmod{1.1.0} [ThrowableTorchMod](throwabletorchmod-1.8-1.1.jar) 
    UC  Torched{5.0.0} [Torched](Torched-5.0.0.jar) 
    UC  TrailMix{5.0.0} [TrailMix](TrailMix-5.0.0.jar) 
    UC  MineMoneyMod{0.1.0} [Mine Money Mod](v0.1.jar) 
    UC  VeinMiner{0.26.1_build.unknown} [Vein Miner](VeinMiner-1.8_0.27.0.unknown.jar) 
    UC  VeinMinerModSupport{0.26.1_build.unknown} [Mod Support](VeinMiner-1.8_0.27.0.unknown.jar) 
    UC  Waila{1.6.0_B1} [Waila](Waila-1.6.0_B1_1.8.1.jar) 
    UC  worldoverhaulmod{1.8_6_1} [World Overhaul Mod](worldoverhaul-1.8-6_1.jar) 
    UC  worldtools{1.1.1} [World Tools](WorldTools_1.8_1.1.1.jar) 
    UC  wormsmod{1.1.2} [Worms Mod](wormsmod-1.8.x-1.1.2.jar) 
    UC  XaeroMinimap{1.5.8} [Xaero's Minimap](xaeros_minimap_v1.5.8_1.8_Forge.jar) 
    UC  youtubers{1.7.0} [Youtubers+ Mod](Youtubers-Mod-1.8.jar) 
    UC  zero_quest{v1.8.5} [Zero Quest](Zero Quest-v1.8.5.jar) 
    UC  ZombieInfection{2.3.0} [Zombie Infection](Zombie Infection-1.8-2.3.0.jar) 
    UC  zombieapocalypse{1.1} [Zombie Apocalypse](zombieapocalypse-1.7.jar) 
    UC  zombie_steak{1.8-1.0.2} [Zombie Steak](ZombieSteak-1.8-1.0.2.jar) 
    Loaded coremods (and transformers): 
NEICorePlugin (NotEnoughItems-1.8-1.0.5.104-universal.jar)
  codechicken.nei.asm.NEITransformer
LoadingScreenLoadPlugin (Better-Loading-Screen-Mod-1.8.jar)
  alexiil.mods.load.coremod.BetterLoadingScreenTransformer
CorePlugin (MakersMark-V2.0.1-MC1.8.jar)
  com.hitchh1k3rsguide.makersmark.asm.ASMTransformer
LoadPlugin (AlexIILLib-1.8.jar)
  alexiil.mods.lib.coremod.ClassTransformer
TransformerLoader (OpenComputers-MC1.8-1.5.11.28-universal.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.8-3.5.3.jar)
  lumien.randomthings.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.59-176.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.115-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCCDeobfPlugin (unknown)

CoreMod (Aroma1997Core-1.8-1.0.3.4.b36.jar)

CodeChickenCorePlugin (CodeChickenCore-1.8-1.0.5.34-universal.jar)
  codechicken.core.asm.InterfaceDependancyTransformer
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CAFMLPlugin (Craftable-Animals-Mod-1.8.jar)
  naruto1310.craftableAnimals.vanilla.CATransformer
VeinMinerCorePlugin (VeinMiner-1.8_0.27.0.unknown.jar)
  portablejim.veinminer.asm.ItemInWorldManagerTransformer
    GL info: ' Vendor: 'Intel Inc.' Version: '2.1 INTEL-8.28.33' Renderer: 'Intel HD Graphics 5000 OpenGL Engine'

**Comment by Delocuro** [comment]
This is a known issue that happens when playing on a Mac, since Apple tries to run the game on it's jive-ass version of java instead of normal Java 8. To fix it, install Java 8, then select the Forge profile in the launcher and click "Edit Profile". Check the box next to "Executable:", delete everything in the text box, and replace it with /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java. Then check the box next to "JVM Arguments:", delete that text, and replace it with -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M. If that doesn't fix the crash, post the new crash report in a new issue and I'll see if I can figure out what's causing it.
