### ISSUE TITLE
Backpack/Satchel Deletes/Duplicates Placed in Items

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#94]
tested in nightly 258

item deletion, to recreate:
- open satchel/backpack
- move it to another player inventory slot or pick it up and place in the same slot
- place items into satchel/backpack inventory
- close satchel/backpack inventory
- after opening items will not be there

item duplication, to recreate:
- open satchel/backpack
- place in item to duplicate
- close satchel/backpack inventory
- open it again
- move it to another player inventory slot or pick it up and place in the same slot
- take out items out of satchel/backpack
- close its inventory
- after opening it again removed item will still be there

it may be the same as "Backpack dupe glitch needs fixing." in #87,
sorry couldn't find details on that one

**Comment by Delocuro** [comment]
Yep, this is indeed the same as the #87 bug. We're planning on having this fixed for 4.1.1, which hopefully will come out before too long.
