### ISSUE TITLE
Diamond Dust Cannot Be Returned to Stack

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#95]
tested in nightly 258
after removing 4 diamond dust from crusher and separating it, diamond dust does not stack

**Comment by Delocuro** [comment]
Huh, interesting. It shouldn't be doing that, so I'll see what's going on.

**Comment by Delocuro** [comment]
Lol, apparently accidentally set the stack size of Diamond Dust to 1 instead of setting the stack size of Crystal Hearts to 1. It's fixed now. :P
