### ISSUE TITLE
Opening Container with Pouch/Backpack in Hand Tweak

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#98]
opening container with pouch/backpack in hand (shift click?) could open container with held item inventory instead of player inventory, could work with machines/crafting table inventories too

**Comment by Delocuro** [comment]
That'd be an awesome feature for convenience, but I have a feeling it'll be SUPER complicated to code. Added to the #47 stretch goals issue for now, so we'll see if we can figure out how to implement it in the future.
