### ISSUE TITLE
Items Gained from Sieving Reshuffle/Change After Inventory Update

### ISSUE THREAD

**Issue by charlie-e09ae35d** [MinestrapTeam/Minestrappolation-4#99]
tested in nightly 258
[video demo](http://gfycat.com/InfatuatedPeskyGrebe)

items put into player inventory by sieve reshuffle/change after picking one of them up

**Comment by Delocuro** [comment]
Already mentioned in #87. Thanks for the demo video, though! Added it to the issue.
